import "./globals.css";
import { Tajawal } from 'next/font/google'; 

const tajawal = Tajawal({
  subsets: ['arabic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-tajawal',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={tajawal.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
